### ISSUE TITLE
Way to use the solution with real angular

### ISSUE THREAD

**Issue by latata** [bahmutov/web-worker-digest-demo#1]
Is there any way do make it work in real AngularJS (1.3) app?

I have template with a lot of bindings and I want to run digests in separated threads so user can interact with interface while digest is running.

**Comment by bahmutov** [comment]
I ported angular 1.3 (and 1.4 I think) to run in the digest cycle, but it did not offer performance gains.
See https://github.com/bahmutov/angular-in-web-worker and follow me on twitter @bahmutov for any more updates and details
